export const userTypes = {
    USER_REGISTER: 'USER_REGISTER',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    
    LOGOUT: 'USER_LOGOUT',

    FETCH_ALL_USERS: 'FETCH_ALL',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILURE: 'FETCH_ALL_USERS_FAILURE',

    DELETE_USER: 'DELETE_USER',
    DELETE_USER_SUCCEED: 'DELETE_USER_SUCCEED',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE'    
}